# Generated by Django 5.2.1 on 2025-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsTripadvisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('id_element_html', models.TextField(blank=True, null=True)),
                ('id_element', models.TextField(blank=True, null=True)),
                ('id_element_html_modal', models.TextField(blank=True, null=True)),
                ('category_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
