# Generated by Django 5.2.1 on 2025-05-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_tripadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagstripadvisor',
            table='tags_tripadvisor',
        ),
    ]
